# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qf < Formula
  desc "Example QuickFIX/Go Applications."
  homepage "https://github.com/quickfixgo/examples"
  version "2.0.25"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/quickfixgo/examples/releases/download/v2.0.25/qf_2.0.25_Darwin_arm64.tar.gz"
      sha256 "2042e287a410cc5afca5c48dee25d9a1befaf908b6b65c8175cb643eada7238a"

      def install
        bin.install "qf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quickfixgo/examples/releases/download/v2.0.25/qf_2.0.25_Darwin_x86_64.tar.gz"
      sha256 "b9ad4c4d88222c8590f1c9e929a82a5e9664ada4144c8517b728492d306bfe2f"

      def install
        bin.install "qf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/quickfixgo/examples/releases/download/v2.0.25/qf_2.0.25_Linux_arm64.tar.gz"
      sha256 "6b982c889a7ba545cb1996d6a6cfe00979dfcda9d7f2d75a2686333fc4c535ef"

      def install
        bin.install "qf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/quickfixgo/examples/releases/download/v2.0.25/qf_2.0.25_Linux_x86_64.tar.gz"
      sha256 "c9bda2c7afda7831a421e0bfa86f06bb75b698be2a17723df9dfce11bf9051ae"

      def install
        bin.install "qf"
      end
    end
  end

  def caveats
    <<~EOS
      Thanks for installing the Quickfix/Go examples
    EOS
  end

  plist_options startup: false

  def plist
    <<~EOS
      <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <dict>
      <key>SuccessfulExit</key>
      <false/>
    </dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>WorkingDirectory</key>
    <string>#{var}</string>
    <key>StandardErrorPath</key>
    <string>#{var}/log/qf.log</string>
    <key>StandardOutPath</key>
    <string>#{var}/log/qf.log</string>
  </dict>
</plist>

    EOS
  end
end
